apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: microservices-demo-dns-error
  namespace: default
spec:
  # どのPodからのDNSクエリを妨害するかを指定
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "frontend"

  # どのような障害を発生させるか
  action: error

  # どのDNSクエリを対象にするか
  patterns:
    - "*service.default.svc.cluster.local"
  
  # 障害を発生させるPodの割合
  # 100%の場合は、選択された全てのPodに障害を注入する
  value: "100"

  # 障害を継続させる時間
  duration: '1m'
